services:
  backend:
    volumes:
      - ./backend:/app/backend
      - ./logs:/app/logs
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"