version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ai-excel-interviewer-backend
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      - ./backend/app:/app/backend/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - ollama
    command: ["python", "main.py"]

  postgres:
    image: postgres:15
    container_name: ai-excel-interviewer-postgres
    restart: always
    environment:
      POSTGRES_DB: ai_excel_interviewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ai-excel-interviewer-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    container_name: ai-excel-interviewer-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  redis_data:
  ollama_data: